kind: Template
apiVersion: v1
metadata:
  name: go-template
  annotations:
    description: "Go Application"
    iconClass: "icon-redis"
    tags: "go,scratch"
objects:


  

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: go-build
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: .

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: go-pipeline
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('agent') {
            stage 'build'
              openshiftBuild(buildConfig: 'go-build', showBuildLogs: 'true')
          }
parameters:
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository
  description: Go Git Repository
  required: true
- name: SOURCE_REPOSITORY_REF
  displayName: Git Branch
  description: Go Git Repository Branch
  value: master
  required: true


